// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesOrders.DAL.Models
{
    public partial class OrderHeader
    {
        public OrderHeader()
        {
            OrderLine = new HashSet<OrderLine>();
        }

        public long orderId { get; set; }
        public string orderNumber { get; set; }
        public string orderType { get; set; }
        public string orderStatus { get; set; }
        public string customerName { get; set; }
        public DateTime createdDate { get; set; }

        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}