// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesOrders.DAL.Models
{
    public partial class OrderLine
    {
        public long lineId { get; set; }
        public long orderId { get; set; }
        public long lineNumber { get; set; }
        public string productCode { get; set; }
        public string productType { get; set; }
        public decimal costPrice { get; set; }
        public decimal salesPrice { get; set; }
        public long quantity { get; set; }

        public virtual OrderHeader order { get; set; }
    }
}