// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SalesOrders.DAL.Models
{
    public partial class SalesOrderDBContext : DbContext
    {
        public SalesOrderDBContext()
        {
        }

        public SalesOrderDBContext(DbContextOptions<SalesOrderDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<OrderHeader> OrderHeader { get; set; }
        public virtual DbSet<OrderLine> OrderLine { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=FAM001251\\SQLEXPRESS01;Initial Catalog=SalesOrderDB;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<OrderHeader>(entity =>
            {
                entity.HasKey(e => e.orderId)
                    .HasName("PK__OrderHea__0809335D8DA59571");

                entity.Property(e => e.createdDate).HasColumnType("datetime");

                entity.Property(e => e.customerName)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.orderNumber)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.orderStatus)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.orderType)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<OrderLine>(entity =>
            {
                entity.HasKey(e => e.lineId)
                    .HasName("PK__OrderLin__32489DA5CD468E37");

                entity.Property(e => e.costPrice).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.productCode)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.productType)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.salesPrice).HasColumnType("decimal(10, 2)");

                entity.HasOne(d => d.order)
                    .WithMany(p => p.OrderLine)
                    .HasForeignKey(d => d.orderId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__OrderLine__order__3B75D760");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}