// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SalesOrders.DAL.Models
{
    public partial class Users
    {
        public long userId { get; set; }
        public string email { get; set; }
        public byte[] passwordHash { get; set; }
        public byte[] passwordSalt { get; set; }
        public DateTime? dateCreated { get; set; }
        public string role { get; set; }
    }
}